package javagame;

public class Part2 {
	public static String INTRO = "Day 43 since the outbreak started. It started out seemingly harmless enough, a \n"
			+ "few fevers here, some more people falling ill there. I didn’t think much of it at \n"
			+ "a time, just a new string of super swine flu mixed with a bit of squirrel AIDS\n"
			+ "is what the media told us. But pretty soon, there were the walking dead on the \n"
			+ "streets."
			+ "\n\n"
			+ "My full name is Control Alt Delete, my friends just call me Control, or at least\n"
			+ "used to before the outbreak. Now they just call me Bob. Actually, they don’t call \n"
			+ "me anything at all anymore. They’re the walkers now, and the dead don’t talk. They \n"
			+ "seem to speak some weird type of sign language that I don’t understand. I tried \n"
			+ "saying hello to one of the walkers, but I don’t think it went all that well since \n"
			+ "he tried to bite my face off.";
	public static String s1 = "I panicked and smashed the walker in the head with a blender, that seemed to put\n"
			+ "an end to him. Then I took a piece of shamwow and cleaned up the mess. That was \n"
			+ "nearly a month ago. Now my water is running out, and my stash of Twinkies is all\n"
			+ "gone. For me that was when I truly cued in that the world had ended. I had long \n"
			+ "dreaded and hoped that this day would not come in my lifetime, but now I have to \n"
			+ "make a trip to the grocery store to get more food.\n\n"
			+ "I looked out the window and saw the streets below, the dead were walking as usual.\n"
			+ "They seem to never tire, they just walk and walk. I grabbed a backpack, and I \n"
			+ "opened up the closet to decide what to wear if I am going to make this journey \n"
			+ "today.";
	public static String s2 = "I stepped outside and came face to face with a walker. Walkers are strong, \n"
			+ "though I was faster than him. I was helped by the clothes I was wearing which \n"
			+ "allowed ease of movement. I succeeded in evading him as I sidestepped him and \n"
			+ "ran off. \n\n"
			+ "I continued my journey to find food and water. I thought I would have \n"
			+ "some luck at the convenience store close to the school, so I decided to go there. \n"
			+ "I approached the store slowly and watched carefully for walkers. The coast appeared\n"
			+ "to be clear. The door to the convenience store seemed to be barred and the windows\n"
			+ "unbroken. I need to find a way to get in, I’ve come too far to leave empty handed.";
	public static String s3 = "As I proceeded into the store I noticed several things. The store was nearly \n"
			+ "empty. Looks like the owners of the store took their own food and fled. The back \n"
			+ "room seemed to be locked though and there was a set of keys under the counter. One \n"
			+ "of them allowed me access to the back room. The room was dark and silent. There were \n"
			+ "still a few boxes of twinkies left on the shelf. But as I reached for the Twinkies, \n"
			+ "a walker popped out of the darkness. ";
	public static String s4 = "I barely escaped with my life at the hands of a walker, but even that will \n"
			+ "seem like a good way to die compared to starvation. I escaped so quickly that I did\n"
			+ "not have time to grab any food. My journey to find food has not yet ended. But first,\n"
			+ "that close encounter with the walker made me decide that I needed a weapon. I \n"
			+ "decided to go to the hardware store across the time in hopes of finding a weapon. \n\n"
			+ "I approached the hardware store with caution. The door was wide open, it looks like \n"
			+ "this place has already been looted. Still, I decided it was worth going in. After \n"
			+ "a brief search I found a small assortment of items that I can use. I only have room \n"
			+ "for one thing though. I need to travel light.";
	public static String s5 = "I found another convenience store nearby. I smashed the window with the hammer and \n"
			+ "proceeded inside. This is the last convenience store nearby. If I do not leave this \n"
			+ "store with food, I will starve tonight. The store was dark, but there didn’t appear \n"
			+ "to be any walkers. This store, like the last one, was nearly empty. But then I \n"
			+ "spotted a couple boxes of Twinkies at the back of the store, I eagerly grabbed \n"
			+ "them and stuffed them into my backpack. Just as I took the last box, I heard a \n"
			+ "voice behind me. \n"
			+ "I turned around to see a man pointing a gun at me. His eyes were bloodshot, his \n"
			+ "hair dirty and messy, and he was unshaven. He had a deranged look on his face as he \n"
			+ "demanded all of the Twinkies in my bag. I had to decide what to do. I could not \n"
			+ "afford to give him all of my Twinkies, I have not come this far only to have my \n"
			+ "food taken by some crazed maniac.";
	public static String s6 = "We walked and walked. I had convinced the gunman that I knew the location of a \n"
			+ "supposed warehouse. In truth, the warehouse doesn’t exist and I have no idea where \n"
			+ "i’m going. I was only postponing my eventual death, I thought to myself. \n\n"
			+ "I was convinced that the gunman would soon see through my lie and kill me. I was \n"
			+ "leading the way and he had his gun pointed at my back at all times. Suddenly, a \n"
			+ "loud car alarm sounded behind us, and a horde of walkers came from behind the \n"
			+ "broken down cars on the road.  Distracted, the gunman turned around, if I am \n"
			+ "going to make my escape, it would have to be now or never. I have to decide \n"
			+ "what to do.";
	public static String s7 = "I began to make my way home. I needed rest badly. And I wanted to find \n"
			+ "somewhere safe to begin dining on the Twinkies. I realized that I was about a twenty \n"
			+ "minute walk from my house. I need to decide a way to get home quickly.";
	public static String s8 = "I finally made it home. I got inside as soon as I could. Just in time, as \n"
			+ "it would appear, it looked like it was about to rain. I ripped open my boxes of \n"
			+ "Twinkies and started to feast on them. I have never tasted anything more delicious \n"
			+ "in my life. I stuffed myself until I could eat no more. I fell asleep on the couch \n"
			+ "like some fat guy who hasn’t paid his rent. I fell asleep with a full stomach for \n"
			+ "once. I would probably have to make another food trip eventually. But not today or \n"
			+ "tomorrow. I’ll be fine for a while.";
}
